# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'floatSettings.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 50, 411, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 70, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.uclTargetInput = QtWidgets.QTextEdit(self.centralwidget)
        self.uclTargetInput.setGeometry(QtCore.QRect(220, 80, 41, 21))
        self.uclTargetInput.setAcceptDrops(True)
        self.uclTargetInput.setAutoFillBackground(False)
        self.uclTargetInput.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.uclTargetInput.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.uclTargetInput.setObjectName("uclTargetInput")
        self.setUclTargetButton = QtWidgets.QPushButton(self.centralwidget)
        self.setUclTargetButton.setGeometry(QtCore.QRect(270, 80, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.setUclTargetButton.setFont(font)
        self.setUclTargetButton.setObjectName("setUclTargetButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 90, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.uclTargetLabel = QtWidgets.QLabel(self.centralwidget)
        self.uclTargetLabel.setGeometry(QtCore.QRect(170, 120, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.uclTargetLabel.setFont(font)
        self.uclTargetLabel.setObjectName("uclTargetLabel")
        self.exportDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.exportDataButton.setGeometry(QtCore.QRect(20, 170, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportDataButton.setFont(font)
        self.exportDataButton.setObjectName("exportDataButton")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 200, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 280, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.importDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.importDataButton.setGeometry(QtCore.QRect(20, 250, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.importDataButton.setFont(font)
        self.importDataButton.setObjectName("importDataButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_7.setFont(font)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.resetDataButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetDataButton.setGeometry(QtCore.QRect(20, 320, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.resetDataButton.setFont(font)
        self.resetDataButton.setObjectName("resetDataButton")
        self.returnToMenuButton = QtWidgets.QPushButton(self.centralwidget)
        self.returnToMenuButton.setGeometry(QtCore.QRect(20, 390, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.returnToMenuButton.setFont(font)
        self.returnToMenuButton.setObjectName("returnToMenuButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Float Settings"))
        self.label_2.setText(_translate("MainWindow", "Upper Control Limit Target: "))
        self.setUclTargetButton.setText(_translate("MainWindow", "Set"))
        self.label_3.setText(_translate("MainWindow", "Current UCL Target:"))
        self.label_4.setText(_translate("MainWindow", "Sets the upper control limit target. Default = 100"))
        self.uclTargetLabel.setText(_translate("MainWindow", "100"))
        self.exportDataButton.setText(_translate("MainWindow", "Export Data"))
        self.label_5.setText(_translate("MainWindow", "Export floating data in .SSG format so that it can be reimported to the program elsewhere "))
        self.label_6.setText(_translate("MainWindow", "Import floating data in .SSG format so that it can be used."))
        self.importDataButton.setText(_translate("MainWindow", "Import Data"))
        self.label_7.setText(_translate("MainWindow", "Resets all floating data"))
        self.resetDataButton.setText(_translate("MainWindow", "Reset all Floating Data"))
        self.returnToMenuButton.setText(_translate("MainWindow", "Return To Menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
